#!/bin/bash
# Login using kubectl

if [ -z "$1" ]; then
  master="mycluster.icp"
else
  master=$1
fi

token=""
while [ "$token" = "" ] do
  token=`curl -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -d "grant_type=password&client_id=rp&client_secret=LDo8LTor&username=admin&password=admin&scope=openid" https://$master:8443/ider/v1/auth/identitytoken --insecure | grep -Po '(?<="id_token":)(.*?)(?=})' | sed 's/\(^"\|"$\)//g'`
  if [ "$token" = "" ] then
     printf "."
     sleep 5
  fi
done

kubectl config set-cluster $master --server=https://10.85.3.102:8001 --insecure-skip-tls-verify=true
kubectl config set-context $master-context --cluster=mycluster.icp
kubectl config set-credentials admin --token=$token
kubectl config set-context $master-context --user=admin --namespace=default
kubectl config use-context $master-context

kubectl get nodes
